import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { OrderStatus } from '@prisma/client';

export class VendorAnalyticsOrderStatusCountDto {
  @ApiProperty({
    description: 'Order status',
    enum: OrderStatus,
    example: OrderStatus.DELIVERED,
  })
  status!: OrderStatus;

  @ApiProperty({
    description: 'Number of orders currently in this status',
    example: 42,
  })
  count!: number;
}

export class VendorDailyTrendDto {
  @ApiProperty({
    description: 'Date of the trend data point (ISO 8601 date string)',
    example: '2024-06-01',
  })
  date!: string;

  @ApiProperty({
    description:
      'Numeric value for the trend, such as daily revenue or order count',
    example: 1250.75,
  })
  value!: number;
}

export class VendorTopProductDto {
  @ApiProperty({
    description: 'Unique identifier of the product',
    example: 'prod_a1b2c3d4e5f6',
  })
  id!: string;

  @ApiProperty({
    description: 'Name of the product',
    example: 'Handcrafted Ceramic Mug',
  })
  name!: string;

  @ApiProperty({
    description: 'Stock-keeping unit (SKU) identifier of the product',
    example: 'MUG-HC-001',
  })
  sku!: string;

  @ApiProperty({
    description: 'Total number of units sold for this product',
    example: 156,
  })
  totalSold!: number;

  @ApiProperty({
    description:
      'Total revenue generated by this product (represented as a decimal string)',
    example: '3899.50',
  })
  revenue!: string;

  @ApiProperty({
    description: 'Current stock quantity available for the product',
    example: 23,
  })
  stock!: number;

  @ApiProperty({
    description:
      'Whether the product is currently active and available for sale',
    example: true,
  })
  isActive!: boolean;
}

export class VendorCustomerSummaryDto {
  @ApiProperty({
    description:
      'Total number of unique buyers who have purchased from the store',
    example: 89,
  })
  totalBuyers!: number;

  @ApiProperty({
    description:
      'Number of buyers who have made more than one purchase (repeat customers)',
    example: 34,
  })
  repeatBuyers!: number;

  @ApiProperty({
    description:
      'Average order value across all orders (represented as a decimal string)',
    example: '45.99',
  })
  averageOrderValue!: string;
}

export class VendorAnalyticsSummaryDto {
  // ── Product metrics ──
  @ApiProperty({
    description:
      'Total number of products in the store, including inactive and draft products',
    example: 120,
  })
  totalProducts!: number;

  @ApiProperty({
    description: 'Number of products currently active and available for sale',
    example: 98,
  })
  activeProducts!: number;

  @ApiProperty({
    description:
      'Number of products with stock quantity below the defined low-stock threshold',
    example: 5,
  })
  lowStockProducts!: number;

  @ApiProperty({
    description:
      'Number of products that are completely out of stock (stock quantity is zero)',
    example: 3,
  })
  outOfStockProducts!: number;

  @ApiProperty({
    description:
      'Total number of product variants across all products in the store',
    example: 310,
  })
  totalVariants!: number;

  // ── Order / revenue metrics ──
  @ApiProperty({
    description: 'Total number of orders placed in the store across all time',
    example: 450,
  })
  totalOrders!: number;

  @ApiProperty({
    description:
      'Number of new orders placed within the selected analytics period',
    example: 28,
  })
  newOrdersInPeriod!: number;

  @ApiProperty({
    description:
      'Total revenue generated across all orders (represented as a decimal string)',
    example: '15250.75',
  })
  totalRevenue!: string;

  @ApiProperty({
    description:
      'Revenue generated within the selected analytics period (represented as a decimal string)',
    example: '1250.50',
  })
  revenueInPeriod!: string;

  @ApiProperty({
    description:
      'Breakdown of order counts grouped by their current status (e.g. pending, completed, cancelled)',
    type: [VendorAnalyticsOrderStatusCountDto],
  })
  orderStatusCounts!: VendorAnalyticsOrderStatusCountDto[];

  // ── Trends ──
  @ApiProperty({
    description:
      'Daily revenue trend data points for the selected analytics period',
    type: [VendorDailyTrendDto],
  })
  revenueTrend!: VendorDailyTrendDto[];

  @ApiProperty({
    description:
      'Daily order count trend data points for the selected analytics period',
    type: [VendorDailyTrendDto],
  })
  orderTrend!: VendorDailyTrendDto[];

  // ── Top products ──
  @ApiPropertyOptional({
    description: 'Top-performing products ranked by revenue or units sold',
    type: [VendorTopProductDto],
  })
  topProducts?: VendorTopProductDto[];

  // ── Customer insights ──
  @ApiPropertyOptional({
    description:
      'Customer purchase behavior summary including unique buyers and repeat purchase metrics',
    type: VendorCustomerSummaryDto,
  })
  customers?: VendorCustomerSummaryDto;

  // ── Frontend-expected aliases ──
  @ApiProperty({
    description: 'Total revenue (alias for totalRevenue)',
    example: '15250.75',
  })
  revenue!: string;

  @ApiProperty({
    description: 'Total order count (alias for totalOrders)',
    example: 450,
  })
  orderCount!: number;

  @ApiProperty({
    description: 'Total units sold across all order items',
    example: 1200,
  })
  productsSold!: number;

  @ApiProperty({
    description: 'Average order value (alias for customers.averageOrderValue)',
    example: '45.99',
  })
  avgOrderValue!: string;

  @ApiPropertyOptional({
    description: 'Recent orders (latest 10)',
    type: [Object],
  })
  recentOrders?: Array<{
    id: string;
    orderNumber: string;
    status: string;
    totalAmount: number;
    createdAt: Date;
    itemCount: number;
  }>;

  @ApiProperty({
    description: 'Conversion rate percentage',
    example: 12.5,
  })
  conversionRate!: number;
}
