services:
  postgres:
    image: postgres:16-alpine
    container_name: nuts_dev_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: nuts_dev
    volumes:
      - nuts_dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nuts_dev || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: nuts_dev_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - nuts_dev_redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    container_name: nuts_dev_redisinsight
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - nuts_dev_redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy

volumes:
  nuts_dev_postgres_data:
    name: nuts_dev_postgres_data
  nuts_dev_redis_data:
    name: nuts_dev_redis_data
  nuts_dev_redisinsight_data:
    name: nuts_dev_redisinsight_data
